### 코틀린의 예외처리 방법을 기록하는 문서

#### throw
- 예외를 발생시킬때 throw 사용
- throw 예외이름(예외메시지) 형태로 사용
  - 자바랑 달리 new를 사용하지 않음

```kotlin
fun main() {
    // Exception 던지기
    val percentage = 200
    if (percentage !in 0..100) {
        // 예외 인스턴스를 만들 때, new를 사용 할 필요없다.
        throw IllegalArgumentException("A percentage value must be between 0 and 100: ${percentage}")
    } else {
        println(percentage)
    }
}
```

### try-catch
- 자바와 동일
- try: throw 발생을 찾음
- catch: 발생한 throw에 대해 연산
- finally: 종료시 항상 실행

```kotlin
import java.io.BufferedReader 
import java.io.StringReader

fun main() { 
  val reader = BufferedReader(StringReader("123")) 
  println(readNumber(reader)) 
} 

fun readNumber(reader: BufferedReader): Int? { // 사용하는 방식은 Java와 같다. try, catch, finally 
  try { 
    val line = reader.readLine() 
    return Integer.parseInt(line) // 숫자 형식이 아닌경우 에러 발생. 
  } 
  catch (e: NumberFormatException) { 
    return null // 숫자 형식이 아님 
  } 
  finally { 
    reader.close() // 정상적이든 오류든 무조건 실행 
  } 
}
```

### try 식
- try문을 식으로 사용 가능
```kotlin
import java.io.BufferedReader 
import java.io.StringReader 

fun main() { // 코틀린에서는 try를 식으로 사용할 수 있다. 
  val num = try { 
    Integer.parseInt(BufferedReader(StringReader("not a number")).readLine()) 
  } 
  catch(e: NumberFormatException) { 
    return // 아무런 값도 나오지 않는다. 
  }
  println(num) 
}
```
